### ISSUE TITLE
increasing handler_read_rnd 

### ISSUE THREAD

**Issue by ebang091** [23-OSSCA-python-mysql-replication/python-mysql-replication#64]
# Problem
Detected increasing handler_read_rnd.
<img width="917" alt="스크린샷 2023-08-25 오후 4 33 04" src="https://github.com/23-OSSCA-python-mysql-replication/python-mysql-replication/assets/108053947/e79f4089-47c9-451f-b83d-1edc60c6abb5">

# Concerns
This can lead to an increase in I/O operations, as the system needs to read through potentially large amounts of data. This can strain the disk subsystem and lead to increased latency for other operations.
Also, Sequentially reading through rows can lead to increased CPU usage, especially if the dataset is large.

# Solution
This can be done by removing 'ORDER BY' statement in table_map event.

<img width="917" alt="스크린샷 2023-08-25 오후 4 43 56" src="https://github.com/23-OSSCA-python-mysql-replication/python-mysql-replication/assets/108053947/d68ff63e-8349-429a-a4ce-d3a53d47cf3a">

**Comment by soulee-dev** [comment]
Title: Optimize `Handler_read_rnd` by removing ORDER BY clause

# Problem
We observed that the `Handler_read_rnd` was continually increasing whenever `__get_table_information` was called upon starting PyMyRepl. The reason was found to be the usage of the `ORDER BY` clause on a non-indexed column within the function.

# Solution
Since the table entries were empty, and `ORDER BY` was being used on a non-indexed column, this led to an increase in the `Handler_read_rnd`. As a remedy, we removed the `ORDER BY` clause from the SQL query and instead used Python's `sort()` method to sort the results. Since `ORDINAL_POSITION` is auto-incremental, this change will return the same sorted results as the original `ORDER BY` clause, without the associated performance penalty.

# Changes
Removed the `ORDER BY` clause from the SQL query within `__get_table_information`.
Implemented sorting using Python's `sort()` method based on `ORDINAL_POSITION`.

# Benefits
Reduces the overhead associated with using the `ORDER BY` clause on a non-indexed column.
Mitigates the increase in `Handler_read_rnd`, leading to improved performance.

**Comment by sean-k1** [comment]
@ebang091 
ordery by를 안쓰면 칼럼스키마가 순서대로 들어오지 않을텐데 ordinal_position 순서를 보장할수있는 방법있나요?
